project:
  type: website
  output-dir: docs
  resources:
    - "assets/*.pdf"

website:
  title: "Bhabilsh Limbu"
  navbar:
    background: primary 
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: CV / Resume
    right:
      - icon: github
        href: https://github.com/bhabs2021
      - icon: linkedin
        href: https://www.linkedin.com/in/bhabilsh-l-1200771b1/